version: "3.4"

# NOTE: that --project-directory .
# must be passed to every docker-compose command
# . is the docker-compose context
#
# NOTE: environment vars are public, and should not contain secrets ^_~
#       use `env_file: [.env]` for secret things.

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data

  svelte-ui:
    depends_on:
      - db
      - valkey
    build:
      context: ./portal/
      dockerfile: Dockerfile
    ports:
      - "6173:6173"
    environment:
      DATABASE_URL: "postgresql://db-user:1234@db:5432/development?schema=public"
      MAIL_SENDER: "LogEmail"
      EMAIL_FROM: "noreply@scriptoria.io"
      DEFAULT_BUILDENGINE_URL: "http://stg-tunnel:8443"
      DEFAULT_BUILDENGINE_API_ACCESS_TOKEN: "${BUILDENGINE_TOKEN}"
      AUTH0_SECRET: "${AUTH0_SECRET}"
      AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_CONNECTION: "${AUTH0_CONNECTION}"
      # MUST be included (the path the application will be accessed on) and MUST NOT have a trailing slash
      ORIGIN: "http://localhost:6173"
  valkey:
    image: valkey/valkey:latest
    command: valkey-server --appendonly yes --appendfilename appendonly.aof --maxmemory-policy noeviction
  stg-tunnel:
    build:
      context: ./deployment/development
      dockerfile: Dockerfile.stg-tunnel
    # yikes
    command: bash -c "cp -r /root/ssh /root/.ssh; chmod -R 600 /root/.ssh; ssh -N -L \*:8443:localhost:\$(ssh aps-stg \"docker ps --format '{{.Names}} {{.Ports}}' | grep -E 'buildengine.*web' | awk -F '->' '{print \\$1}' | awk -F ':' '{print \\$2}'\") aps-stg"
    volumes:
      - ~/.ssh:/root/ssh
